### ISSUE TITLE
Limit number of concurrent connections

### ISSUE THREAD

**Issue by paolovolpi** [splunk/pion#15]
Hi, 
would be possible to limit the number of concurrent connections?

I'm working on a solution to implement that feature but I didn't find yet a clean one.

My current solution:
 * add a max_concurrent_connections member variable in tcp_server with default value = 0 and passed by the user in ctor.

* in server::listen , add a parameter bool histeresisTrigger with default value = false

* in server::listen , add the following check at the begin

```cpp
if(histeresisTrigger)
{
    if((m_max_concurrent_connections) &&
    (m_con_pool.size() != m_max_concurrent_connections -10)) {
        return;
    } else {
         if ((m_max_concurrent_connections) &&
        (m_conn_pool.size() == m_max_concurrent_connections)) {
            return;
    }
}
```

*  in server::finish_connection add the following code inside the else branch at the end :

        if ((m_is_listening) &&
            (m_max_concurrent_connections) &&
            (m_conn_pool.size() == m_max_concurrent_connections -10)) {
                server_lock.release();
               listen(true);
            }

Do you think this feature would be useful? 
Thx

**Comment by mikedickey** [comment]
Makes sense to me. Please sign CLA and submit a pull request if you would like.
