### ISSUE TITLE
cmake find_package(Threads)

### ISSUE THREAD

**Issue by breese** [splunk/pion#53]
CMakeLists.txt currently uses find_package(Threads REQUIRED) to check for -lpthreads etc. However, some platforms have all the thread functions in the run-time libraries, and therefore have no extra thread library. The cmake build fails on these platforms because of the REQUIRED option. If you remove this option, then it works.

**Comment by mikedickey** [comment]
Please sign CLA and submit a pull request if you would like to fix this.
