### ISSUE TITLE
cmake CMAKE_SOURCE_DIR versus PROJECT_SOURCE_DIR

### ISSUE THREAD

**Issue by breese** [splunk/pion#54]
I am trying to integrate pion into a larger cmake-based project via add_subdirectory(pion pion-build).

This is rather difficult because the pion CMakeLists.txt uses CMAKE_ variables instead of the equivalent PROJECT_ variables. One unfortunate consequence is that the pion policy of not being able to build in-source escalates to the larger project.

If the pion CMakeLists.txt used the PROJECT_ variables instead, then I can build pion outside-source with the "pion-build" workaround in the add_subdirectory() above.

The variables that I needed to changes were:

* CMAKE_SOURCE_DIR -> PROJECT_SOURCE_DIR
* CMAKE_BINARY_DIR -> PROJECT_BINARY_DIR

And for good measure (see also #36) I also needed to remove the /Bin part of COMMON_BIN_PATH.

**Comment by mikedickey** [comment]
Please sign CLA and submit a pull request if you would like to fix this.
