### ISSUE TITLE
behavioral change with parse_uri?

### ISSUE THREAD

**Issue by rimmartin** [splunk/pion#57]
Hi,

I've been using parse_uri to decide if there is a uri and if not do something different.
Previously
std::string potentialUri="ethanol.xml"
would reject and let me know it wasn't a uri
```
        if(!pion::http::parser::parse_uri(uri, proto, host, port, path, query))
        {
            return false;
        }
```
but not it satisfies but there is no host or port;
Maybe I should now decide on the results instead of the return boolean?

**Comment by mikedickey** [comment]
Perhaps you could check the return value and that proto is not empty?
