### ISSUE TITLE
Build with MinGW  fails

### ISSUE THREAD

**Issue by PetrovskYYY** [splunk/pion#58]
Tried to build pion with MinGW (gcc 4.8.1) under Windows 7 64 bit (MSYS environment).
autogen.sh runs normal, but it generates configure file with two errors (probably one error duplicated) - there is empty else ...fi section at lines before line 17839 and 17938 (in my case). Had to remove lines with else.

After this issue is corrected configure runs untill it comes to boost library. 

    checking for boostlib >= 1.35... configure: error: We could not detect the boost  libraries (version 1.35 or higher). If you have a staged boost library (still not installed) please specify $BOOST_ROOT in your environment and do not give a PATH to --with-boost option.  If you are sure you have boost installed, then check your version number looking in <boost/version.hpp>. See http://randspringer.de/boost for more documentation.

My boost library is located in non-standard location (actually I have several boost libraries of different versions). I had tried to define BOOST_ROOT environment variable as it is written in error message, but without success. 

    export BOOST_ROOT="/c/MinGW/boost_1_55_0/boost"

When i move folders with boost header files to include dir this test passes. But I do not know where should i put boost library (*.a) files.

I had also tried to define --libdir and --includedir in configure parameters without any success. (with ":" and " " as delimiters) 

    ./configure --libdir="/C/MinGW/lib /C/MinGW/boost_1_55_0" --includedir="/C/MinGW/include /C/MinGW/boost_1_55_0"

It looks like there is no effect of this parameters on configure script execution
Could you help me to configure build environment? 
Maybe I am doing something wrong. 
I am very interested in pion library but still unable to build it.

**Comment by mikedickey** [comment]
Supposedly, MinGW support is fixed by https://github.com/splunk/pion/pull/74/ (although I have not verified)
