### ISSUE TITLE
Does the pion server support compression via the 'Accept-Encoding: gzip' directive?

### ISSUE THREAD

**Issue by goran333** [splunk/pion#59]
I built the pion 5.0.6 library with zlib support and wrote a sample HTTP server. The server is a dummy server that always returns a JSON payload. 

When I issue a HTTP get request to the server with "Accept-Encoding: gzip" set in the header, I was hoping to get gzipped JSON in the response but server always returns plain JSON. 

Am I missing something here? Do I need to set a parameter on the pion::http::server that will turn on the gzip support?

**Comment by mikedickey** [comment]
The library does not automatically compress the payload for you. You'll need to use something like Boost.Iostream's gzip_compressor to do this. See http://www.boost.org/doc/libs/1_59_0/libs/iostreams/doc/index.html
