### ISSUE TITLE
cookie is not copied in copy constructor of class message

### ISSUE THREAD

**Issue by aj3423** [splunk/pion#69]
the **m_cookie_params** is not copied in **message**,  so 

    	pion::http::response resp_1(req);
	resp_1.receive(con, err); //  resp_1  contains cookie
	pion::http::response resp_2 = resp_1; // cookie is not copied to resp_2

**Comment by mikedickey** [comment]
Fixed in 5ba80263e77221adf3deae7b492695ea93bb39c1
