### ISSUE TITLE
shared-lib-without-dependency-information and missing-call-to-setgroups

### ISSUE THREAD

**Issue by awissu** [splunk/pion#80]
Hello!
I to build package (pion-5.0.7) and OBS output gave me the following warning:

pion-plugins.i586: W: shared-lib-without-dependency-information /usr/lib/pion/plugins/hasNoCreate.so

libpion-5_0.i586: W: missing-call-to-setgroups-before-setuid /usr/lib/libpion-5.0.so
This executable is calling setuid and setgid without setgroups or initgroups.
There is a high probability this mean it didn't relinquish all groups, and
this would be a potential security issue to be fixed. Seek POS36-C on the web
for details about the problem.

Thank you for the attention, hope this report helps development.

**Comment by vshcherbakov** [comment]
Hello,

hasNoCreate is a test plugin that's not used in production, so I believe it's safe to ignore these warnings.

Thanks for reporting it though!

--Vladimir
