### ISSUE TITLE
Linux 64 build failure 

### ISSUE THREAD

**Issue by ruddy32** [splunk/pion#96]
There is an error while building library on Linux. The header file <include/pion/config.hpp> does not exists while <include/pion/config.hpp.win> or <include/pion/config.hpp.xcode> exists. Why <config.hpp> is not created during configuration step ?

Building context :
>System uname: Linux-3.14.27-x86_64-Intel-R-_Core-TM-_i7-2670QM_CPU_@_2.20GHz-gentoo-14.16.2
>sh bash 4.3_p33-r2
>ld GNU ld (Gentoo 2.24 p1.4) 2.24
>app-shells/bash:          4.3_p33-r2::gentoo
>dev-util/cmake:           3.2.2::gentoo
>dev-util/pkgconfig:       0.28-r2::gentoo
>sys-devel/autoconf:       2.13::gentoo, 2.69::gentoo
>sys-devel/automake:       1.11.6-r1::gentoo, 1.13.4::gentoo, 1.15::gentoo
>sys-devel/gcc:            4.8.4::gentoo
>sys-devel/gcc-config:     1.7.3::gentoo
>sys-devel/libtool:        2.4.6::gentoo
>sys-devel/make:           4.1-r1::gentoo
>sys-kernel/linux-headers: 3.18::gentoo (virtual/os-headers)
>sys-libs/glibc:           2.20-r2::gentoo

Build info:
> * Running eautoreconf in '/var/calculate/tmp/portage/dev-cpp/pion-5.0.7/work/pion-5.0.7' ...
> * Running libtoolize --install --copy --force --automake ...
> [ ok ]
> * Running aclocal -I m4 -I build ...
> [ ok ]
> * Running autoconf --force ...
> [ ok ]
> * Running autoheader ...
> [ ok ]
> * Running automake --add-missing --copy --foreign --force-missing ...
> [ ok ]
> * Running elibtoolize in: pion-5.0.7/
> * Running elibtoolize in: pion-5.0.7/m4/
> *   Applying portage/1.2.0 patch ...
> *   Applying sed/1.5.6 patch ...
>shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
>shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
>job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
>chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
> *      myeconfargs =>  --enable-option-checking --disable-silent-rules --disable-dependency-tracking --disable-fast-install --without-gnu-ld --disable-libtool-lock --disable-doxygen-man --disable-doxygen-rtf --disable-doxygen-xml --disable-doxygen-html --disable-doxygen-pdf --with-boost --without-debug --disable-tests --with-zlib --without-bzlib --with-openssl --enable-logging --with-ostream-logging --without-log4cplus --without-log4cxx --without-log4cpp
>>>> Working in BUILD_DIR: "/var/calculate/tmp/portage/dev-cpp/pion-5.0.7/work/pion-5.0.7"
>checking for a BSD-compatible install... /usr/bin/install -c
>checking whether build environment is sane... yes
>checking for a thread-safe mkdir -p... /bin/mkdir -p
>checking for gawk... gawk
>checking whether make sets $(MAKE)... yes
>checking whether make supports nested variables... yes
>checking whether make supports nested variables... (cached) yes
>checking for style of include used by make... GNU
>checking for x86_64-pc-linux-gnu-gcc... x86_64-pc-linux-gnu-gcc
>checking whether the C compiler works... yes
>checking for C compiler default output file name... a.out
>checking for suffix of executables...
>checking whether we are cross compiling... no
>checking for suffix of object files... o
>checking whether we are using the GNU C compiler... yes
>checking whether x86_64-pc-linux-gnu-gcc accepts -g... yes
>checking for x86_64-pc-linux-gnu-gcc option to accept ISO C89... none needed
>checking whether x86_64-pc-linux-gnu-gcc understands -c and -o together... yes
>checking dependency style of x86_64-pc-linux-gnu-gcc... none
>checking build system type... x86_64-pc-linux-gnu
>checking host system type... x86_64-pc-linux-gnu
>checking how to print strings... printf
>checking for a sed that does not truncate output... /bin/sed
>checking for grep that handles long lines and -e... /bin/grep
>checking for egrep... /bin/grep -E
>checking for fgrep... /bin/grep -F
>checking for ld used by x86_64-pc-linux-gnu-gcc... /usr/x86_64-pc-linux-gnu/bin/ld
>checking if the linker (/usr/x86_64-pc-linux-gnu/bin/ld) is GNU ld... yes
>checking for BSD- or MS-compatible name lister (nm)... /usr/bin/x86_64-pc-linux-gnu-nm -B
>checking the name lister (/usr/bin/x86_64-pc-linux-gnu-nm -B) interface... BSD nm
>checking whether ln -s works... yes
>checking the maximum length of command line arguments... 1572864
>checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
>checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
>checking for /usr/x86_64-pc-linux-gnu/bin/ld option to reload object files... -r
>checking for x86_64-pc-linux-gnu-objdump... objdump
>checking how to recognize dependent libraries... pass_all
>checking for x86_64-pc-linux-gnu-dlltool... dlltool
>checking how to associate runtime and link libraries... printf %s\n
>checking for x86_64-pc-linux-gnu-ar... x86_64-pc-linux-gnu-ar
>checking for archiver @FILE support... @
>checking for x86_64-pc-linux-gnu-strip... x86_64-pc-linux-gnu-strip
>checking for x86_64-pc-linux-gnu-ranlib... x86_64-pc-linux-gnu-ranlib
>checking command to parse /usr/bin/x86_64-pc-linux-gnu-nm -B output from x86_64-pc-linux-gnu-gcc object... ok
>checking for sysroot... no
>checking for a working dd... /bin/dd
>checking how to truncate binary pipes... /bin/dd bs=4096 count=1
>checking for x86_64-pc-linux-gnu-mt... no
>checking for mt... no
>checking if : is a manifest tool... no
>checking how to run the C preprocessor... x86_64-pc-linux-gnu-gcc -E
>checking for ANSI C header files... yes
>checking for sys/types.h... yes
>checking for sys/stat.h... yes
>checking for stdlib.h... yes
>checking for string.h... yes
>checking for memory.h... yes
>checking for strings.h... yes
>checking for inttypes.h... yes
>checking for stdint.h... yes
>checking for unistd.h... yes
>checking for dlfcn.h... yes
>checking for objdir... .libs
>checking if x86_64-pc-linux-gnu-gcc supports -fno-rtti -fno-exceptions... no
>checking for x86_64-pc-linux-gnu-gcc option to produce PIC... -fPIC -DPIC
>checking if x86_64-pc-linux-gnu-gcc PIC flag -fPIC -DPIC works... yes
>checking if x86_64-pc-linux-gnu-gcc static flag -static works... yes
>checking if x86_64-pc-linux-gnu-gcc supports -c -o file.o... yes
>checking if x86_64-pc-linux-gnu-gcc supports -c -o file.o... (cached) yes
>checking whether the x86_64-pc-linux-gnu-gcc linker (/usr/x86_64-pc-linux-gnu/bin/ld -m elf_x86_64) supports shared libraries... yes
>checking whether -lc should be explicitly linked in... no
>checking dynamic linker characteristics... GNU/Linux ld.so
>checking how to hardcode library paths into programs... immediate
>checking for shl_load... no
>checking for shl_load in -ldld... no
>checking for dlopen... no
>checking for dlopen in -ldl... yes
>checking whether a program can dlopen itself... yes
>checking whether a statically linked program can dlopen itself... no
>checking whether stripping libraries is possible... yes
>checking if libtool supports shared libraries... yes
>checking whether to build shared libraries... yes
>checking whether to build static libraries... no
>checking for x86_64-pc-linux-gnu-doxygen... no
>checking for doxygen... no
>configure: WARNING: doxygen not found - will not generate any doxygen documentation
>checking for x86_64-pc-linux-gnu-perl... no
>checking for perl... /usr/bin/perl
>checking for x86_64-pc-linux-gnu-g++... x86_64-pc-linux-gnu-g++
>checking whether we are using the GNU C++ compiler... yes
>checking whether x86_64-pc-linux-gnu-g++ accepts -g... yes
>checking dependency style of x86_64-pc-linux-gnu-g++... none
>checking how to run the C++ preprocessor... x86_64-pc-linux-gnu-g++ -E
>checking for ld used by x86_64-pc-linux-gnu-g++... /usr/x86_64-pc-linux-gnu/bin/ld -m elf_x86_64
>checking if the linker (/usr/x86_64-pc-linux-gnu/bin/ld -m elf_x86_64) is GNU ld... yes
>checking whether the x86_64-pc-linux-gnu-g++ linker (/usr/x86_64-pc-linux-gnu/bin/ld -m elf_x86_64) supports shared libraries... yes
>checking for x86_64-pc-linux-gnu-g++ option to produce PIC... -fPIC -DPIC
>checking if x86_64-pc-linux-gnu-g++ PIC flag -fPIC -DPIC works... yes
>checking if x86_64-pc-linux-gnu-g++ static flag -static works... yes
>checking if x86_64-pc-linux-gnu-g++ supports -c -o file.o... yes
>checking if x86_64-pc-linux-gnu-g++ supports -c -o file.o... (cached) yes
>checking whether the x86_64-pc-linux-gnu-g++ linker (/usr/x86_64-pc-linux-gnu/bin/ld -m elf_x86_64) supports shared libraries... yes
>checking dynamic linker characteristics... (cached) GNU/Linux ld.so
>checking how to hardcode library paths into programs... immediate
>checking for C++ compiler vendor... gnu
>checking for specific CPU architecture... no
>checking for debugging... no
>checking for plug-ins directory... /usr/share/pion/plugins
>checking for boostlib >= 1.35... yes
>checking boost library extension... -mt
>checking for boost::date_time library... ok
>checking for boost::system library... ok
>checking for boost::thread library... ok
>checking for boost::filesystem library... ok
>checking for boost::regex library... ok
>configure: Unit tests are disabled
>checking for cygwin directory... no
>checking for malloc_trim() support... yes
>checking unordered_map usability... no
>checking unordered_map presence... no
>checking for unordered_map... no
>checking tr1/unordered_map usability... yes
>checking tr1/unordered_map presence... yes
>checking for tr1/unordered_map... yes
>checking if unordered_map is ok... ok
>checking for gzip compression support (zlib)... yes
>checking zlib.h usability... yes
>checking zlib.h presence... yes
>checking for zlib.h... yes
>checking linking with zlib... ok
>checking for bzip2 compression support (bzlib)... no
>checking for SSL support (openssl)... yes
>checking openssl/ssl.h usability... yes
>checking openssl/ssl.h presence... yes
>checking for openssl/ssl.h... yes
>checking linking with openssl... ok
>configure: Building Pion with support for SSL (using OpenSSL)
>configure: Using std::ostream for logging
>checking that generated files are newer than configure... done
>configure: creating ./config.status
>config.status: creating pion.pc
>config.status: creating Makefile
...

Build error:
>libtool: compile:  x86_64-pc-linux-gnu-g++ -DHAVE_CONFIG_H -I. -I../include/pion -I../include -pthread -D_REENTRANT -I/usr/include -O2 -march=x86-64 -pipe -DPION -O2 -ggdb -Wall -Wno-strict-aliasing -DNDEBUG -c spdy_parser.cpp  -fPIC -DPIC -o .libs/spdy_parser.o
>In file included from logger.cpp:10:0:
>../include/pion/logger.hpp:238:25: error: variable ‘pion::PION_API pion::logger’ has initializer but >incomplete type
>         struct PION_API logger {
>                         ^
>../include/pion/logger.hpp:238:25: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11 [enabled by default]
>../include/pion/logger.hpp:239:13: error: expected primary-expression before ‘enum’
>             enum log_priority_type {
>             ^
>../include/pion/logger.hpp:239:13: error: expected ‘}’ before ‘enum’
>../include/pion/logger.hpp:239:13: error: expected ‘,’ or ‘;’ before ‘enum’
>../include/pion/logger.hpp:243:20: error: expected class-name before ‘(’ token
>             ~logger() {}
>                    ^
>../include/pion/logger.hpp:244:24: error: ISO C++ forbids declaration of ‘logger’ with no type >[-fpermissive]
>             logger(void) : m_name("pion") {}
>                        ^
>../include/pion/logger.hpp: In function ‘int pion::logger()’:
>../include/pion/logger.hpp:244:28: error: only constructors take member initializers
>             logger(void) : m_name("pion") {}
>                            ^
.

**Comment by snikulov** [comment]
Can be dup for #77

**Comment by ruddy32** [comment]
May be.
Configuration help tells that directory is optional. Dependent libraries are in the default library directory "/usr/lib64". Is it necessary to specify this directory ?

**Comment by ruddy32** [comment]
Gentoo packaging is based on ebuild script.
With pion-5.0.6, the script implements:
> src_prepare() {
>    autotools-utils_src_prepare
> }
autotools-utils_src_prepare is calling autoconf, autoheader, etc.
and with pion-5.0.7, the new script implements:
> src_prepare() {
>    ./autogen.sh
> }
It fixes the problem.
