### ISSUE TITLE
pion does not compile against boost 1.58

### ISSUE THREAD

**Issue by mkm85** [splunk/pion#97]
There seems to be a disrepancy between callback definitions and actual implementation. Somtimes shared_ptr is passed by reference, some times not.

A fix can be found here:  https://github.com/mkm85/pion/commit/9933e4e04d02b59d38dc15219e61dc5a5326d1ab

**Comment by mikedickey** [comment]
I believe this was fixed by way of another patch that I recently merged.. at least, I am able to build OK using Boost 1.58 provided by brew on OSX Yosemite.
